### ISSUE TITLE
errors running steps in README

### ISSUE THREAD

**Issue by larryhengl** [AmerMathSoc/AMS-Lens#32]
Hi, simply following the steps in the README (clone, install, start) I'm seeing an error in the browser at 127.0.0.1:4001

<img width="707" alt="screen shot 2016-02-24 at 5 54 35 pm" src="https://cloud.githubusercontent.com/assets/2637196/13307419/f2f85f78-db1f-11e5-81e3-04fb6b590251.png">

using 
node 5.5.0
npm 3.3.12

**Comment by pkra** [comment]
Thanks for the report. This seems due to recent changes. 

The code at https://github.com/AmerMathSoc/AMS-Lens/commit/ce6817d030a47c96d1b1a2c0e1629f62d4fffa57 works for me with the same node/npm versions.

@michael do you have an immediate idea what introduced this bug?

**Comment by pkra** [comment]
@michael  this could also be an upstream issue; with the dependencies from https://github.com/AmerMathSoc/AMS-Lens/commit/ce6817d030a47c96d1b1a2c0e1629f62d4fffa57 current master works ok with the default sample.

**Comment by pkra** [comment]
Ok, seems like a bug in Lens itself; it doesn't check if `<back>` exists. 

@larryhengl if you manually add an empty `<back />` tag before the closing `</body>` tag in the default sample (`data/arxiv-0312227.xml`) does the document render for you?

**Comment by larryhengl** [comment]
yes!  that does the trick.  thanks, looks great!

**Comment by pkra** [comment]
FYI I've submitted a patch upstream.

**Comment by pkra** [comment]
@larryhengl thanks for the feedback!

**Comment by pkra** [comment]
Merged upstream and PR waiting to update our dependency here.

**Comment by larryhengl** [comment]
awesome! thanks for the quick turnaround @pkra. feel free to close this issue whenever it is suitable. cheers!

**Comment by pkra** [comment]
No problem. Luckily, it had an easy fix. The issue will automatically close when the PR gets merged.
