### ISSUE TITLE
kwd handling does not support complex markup

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/AMS-Lens#56]
Keywords can contain complex markup (in particular inline-equations). 

Unfortunately, Lens seems to just grab innerText (needs checking).

**Comment by pkra** [comment]
Filed upstream.

**Comment by pkra** [comment]
PS: funding-info is the same way since I based the code off of kwd.

**Comment by obuchtala** [comment]
Fixed via https://github.com/elifesciences/lens/pull/175 and https://github.com/AmerMathSoc/AMS-Lens/pull/66
