### ISSUE TITLE
Can't push to this repository

### ISSUE THREAD

**Issue by obuchtala** [AmerMathSoc/AMS-Lens#60]
@pkra can u fix this plz?

**Comment by pkra** [comment]
No, because I already did. You must have an invite to this repo somewhere.

**Comment by pkra** [comment]
To be clear: GitHub won't let me do this (to avoid spamming, I think). If you can't find the invite, we need to file an issue with GitHub.

**Comment by obuchtala** [comment]
Can you then revoke my permissions, and re-add me.
It would be the first time, that I need to 'accept' an invitation on a github repository.

**Comment by pkra** [comment]
As I was saying, I can't because GitHub does not allow me to re-try. If I look up your user name to add you, it will be shown as "invitation pending" and there's no interface to revoke the invite or retry.

**Comment by obuchtala** [comment]
strange.

**Comment by pkra** [comment]
Ah! Found it eleswhere.

**Comment by pkra** [comment]
You should have a new invite.

**Comment by obuchtala** [comment]
Fine. Thx!

**Comment by obuchtala** [comment]
Is working now.
